### ISSUE TITLE
Do you need to set a starting seed for repeatability?

### ISSUE THREAD

**Issue by akeyel** [CDCgov/ww-inference-model#106]
## Describe the improvement that needs to be made
How repeatable are the MCMC model runs? I.e. would you get different results if you ran the model multiple times?
Would using set.seed() be honored by the underlying STAN code, or would it just get ignored?

**Comment by dylanhmorris** [comment]
The Stan PRNG seed is set separately from the R PRNG seed. Within the package, it is configured via `get_mcmc_options`
https://cdcgov.github.io/ww-inference-model/reference/get_mcmc_options.html

It strikes me that:

1. This should be better documented.
2. Currently, there is a fixed default (`seed = 123`). That should not be the case. I think I would advocate for default `seed = NULL`. 
3. There's also the matter of seeding the random initial values. See #107.

**Comment by dylanhmorris** [comment]
This is addressed as of #175
