### ISSUE TITLE
Fix `test_get_stan_data` so random failure doesn't occur

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#142]
## Problem

Every so often this test fails despite setting the seed for reproducibility. I believe is because we are using `rnorm()` to generate concentration values and then checking for outliers, and then checking for the number of rows in the final dataset. Have seen it a few times in CI. My inclination is that the test is hard coded and should be made more robust.

**Comment by dylanhmorris** [comment]
It doesn't look to me as though the seed is actually set?

**Comment by kaitejohnson** [comment]
Oh wow yep I thought that was set.seed
