### ISSUE TITLE
move `cmdstanr` to suggests

### ISSUE THREAD

**Issue by gvegayon** [CDCgov/ww-inference-model#188]
Should do the following:

- Move `cmdstanr` to `Suggests`.
- Add a standard check using `requireNamespace()` in functions calling `cmdstanr`.
- Add an R CMD check that skips installing `cmdstanr` to ensure the errors work as expected, i.e., `R CMD check` will not fail if the package is not present.

**Comment by dylanhmorris** [comment]
I don't really think `cmdstanr` can be a `Suggests` given how the package works at present. It's integral to the package functionality.

**Comment by gvegayon** [comment]
That's right, @dylanhmorris, but this is necessary if the package ever makes it to CRAN. `EpiNow2` has a similar theme: depends on `cmdstanr` but is a `Suggests` dependency.

**Comment by dylanhmorris** [comment]
@seabbs can correct me, but I believe `EpiNow2` can fit models with `rstan` (which is on CRAN, and is under `Imports:`) without the need for `cmdstanr` to be installed.

**Comment by seabbs** [comment]
Yes in `EpiNow2` it is a true suggests. `cmdstanr` being core to `epinowcast` is why its not on CRAN. That being said maybe the CRAN gods would be okay with this (but I haven't tried).

**Comment by dylanhmorris** [comment]
Okay to close as won't do for now @kaitejohnson?
