### ISSUE TITLE
Modify `plot` methods

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#200]
## Goal
Realizing two issues with the current `plot()` method as we run on real data:
1. Lots of sites doesn't print well bc we are including the x axis dates in every facet. Might even want the option to turn off dates? 
2. The hospital admissions plots need evaluation data -- this should be optional since it won't be available in real-time!

**Comment by gvegayon** [comment]
> The hospital admissions plots need evaluation data -- this should be optional since it won't be available in real-time!

Yes!

> Lots of sites doesn't print well bc we are including the x axis dates in every facet. Might even want the option to turn off dates?

The beauty of `ggplot2` is that we could return a rather minimal `grob` (graphical object) which users can tailor afterwards; so yeah, we could have many optional, including dates.
