### ISSUE TITLE
Deployment failure

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#209]
Deploying the gh-pages after tagging the release seems to have failed. 
![image](https://github.com/user-attachments/assets/2f4bc9cc-1399-40e4-9678-68b8b838dd27)

https://github.com/CDCgov/ww-inference-model/actions/runs/11149867662 Link to failed job here

**Comment by gvegayon** [comment]
Solvable:

![image](https://github.com/user-attachments/assets/b13c773d-8ad0-4ea5-8b2d-0909a0b54221)

**Comment by kaitejohnson** [comment]
@dylanhmorris Did you fix this and if so should I close?
