### ISSUE TITLE
Bug in wwvals$ww_sampled_times

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#226]
As described by @akeyel via email. 

After further investigation, I believe the issue was that there were multiple `site_pop` per a single site being passed into `wwinference`. I thought that I had a check for this in `preprocess_ww_data()` but when I reran it didn't seem to flag. 

So this issue needs to edit and retest the `checkers`/`validate` to make sure there is one unique population size per site, or add a new checker if it is missing.

**Comment by gvegayon** [comment]
I think this should be addressed in the `validate_ww_conc_data()` function here https://github.com/CDCgov/ww-inference-model/blob/629a9c0fe6c46f5b71fede329278cf55fcc55d99/R/validate.R#L77-L81.

**Comment by kaitejohnson** [comment]
It would just be that one!
