### ISSUE TITLE
Set up caching of `wwinference.Rmd` vignette in R-cmd-check

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#23]
## Goal
Set up caching of vignette build. Right now, this takes a long time because it has to run the full example model.

## Requirements
- [ ] if nothing that impacts the vignette gets updated, we want to cache the vignette build

**Comment by kaitejohnson** [comment]
OK, this might be a bit of a lift so other options are to set up some set cadence of updating like is done in epinowcast:
https://github.com/epinowcast/epinowcast/pull/494
https://github.com/epinowcast/epinowcast/pull/497

**Comment by dylanhmorris** [comment]
Going to close this as resolved by #78 and open a new issue to discuss whether the website build needs speedup or is fine as is.
