### ISSUE TITLE
Parameterize weekday effect with a Dirichlet

### ISSUE THREAD

**Issue by kaitejohnson** [CDCgov/ww-inference-model#42]
## Problem
We are currently using a constrained simplex for the weekday effect with a normal prior for the mean of each element. It isn't clear how stan implements this under the hood, and would be better to sample directly from a Dirichlet

Thanks for the flag @damonbayer @dylanhmorris

**Comment by seabbs** [comment]
I assume you tried this before and couldn't get it to work as it is what the reference implementation does?

**Comment by kaitejohnson** [comment]
I don't even think I tried!
