### ISSUE TITLE
Posterior predictive distributions should be piecewise constant?

### ISSUE THREAD

**Issue by athowes** [CDCgov/ww-inference-model#60]
<img width="813" alt="image" src="https://github.com/user-attachments/assets/41b3ff66-8933-4138-b230-47938ed1c624">

In https://github.com/cdcent/cfa-spatial-ww-internal/issues/5#issue-2458143691 @cbernalz created these plots.

The red line is the data, and the other coloured lines I think are draws from the posterior predictive distribution. I think these draws from the posterior predictive distribution should be piecewise constant (like the data). This might be possible using e.g. `geom_step` (or otherwise not using `geom_line` to connect up the shortest path).

As I understand it the code for these plots was from somewhere in this package.

**Comment by dylanhmorris** [comment]
#62 fixes this. Also noting that it is also important to make sure one is not comparing an infection-feedback-adjusted $\mathcal{R}(t)$, which will indeed vary day-to-day to an unadjusted weekly $\mathcal{R}(t)$
