### ISSUE TITLE
Infection feedback strength for simulated data should be configurable

### ISSUE THREAD

**Issue by dylanhmorris** [CDCgov/ww-inference-model#65]
Right now it is fixed at 0. There is also an extraneous `if_feedback` variable that appears not to be used.

https://github.com/CDCgov/ww-inference-model/blob/142b5572e66dd09893d646a558b478985baeb900/R/generate_simulated_data.R#L229-L230

The `infection_feedback` value is then documented as a binary RE: whether to use, but that appears incorrect per the Stan source file. It appears it is actually the strength of the feedback.
https://github.com/CDCgov/ww-inference-model/blob/142b5572e66dd09893d646a558b478985baeb900/R/generate_simulated_data.R#L299-L307

https://github.com/CDCgov/ww-inference-model/blob/142b5572e66dd09893d646a558b478985baeb900/inst/stan/functions/infections.stan#L60-L88

**Comment by kaitejohnson** [comment]
Ooph good catch... I can change this in #29 ?

**Comment by dylanhmorris** [comment]
Fixed by #29
